"""Mako template for alembic migration scripts."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a211abb9bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
