"""Mako template for alembic migration scripts."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bad4e51f2a'
down_revision = 'e1b2c3d4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
