"""Mako template for alembic migration scripts."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842a4504746d'
down_revision = 'd9a8f3c1b2e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'discount_amount')
    # ### end Alembic commands ###
